language: java
jdk:
  - openjdk8

# 오직 master 브랜치에 push 될때만 수행
branches:
  only:
    - master

# 같은 의존성은 다음 배포때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# push 되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jhl3646@gmail.com